#ifndef DEFERREDATTRIBUTEINTERPOLATIONSHADING_ALGORITHMS_OPTION_DECLARATION_MACROS
#define DEFERREDATTRIBUTEINTERPOLATIONSHADING_ALGORITHMS_OPTION_DECLARATION_MACROS

#define DECLARE_OPTION(name, defaultValue) \
    bool& name = (options[#name] = defaultValue);

#define DECLARE_SHADER_ONLY_OPTION(name, defaultValue) \
    options[#name] = defaultValue;

#endif /* DEFERREDATTRIBUTEINTERPOLATIONSHADING_ALGORITHMS_OPTION_DECLARATION_MACROS */
